server {
    listen 80;
    server_name _;
    client_max_body_size 2g;

    root /usr/share/nginx/html;
    index index.html;

    location /login {
        proxy_pass http://server:8000;
    }

    location /files {
        proxy_pass http://server:8000;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
