services:
  server:
    build:
      context: ./server
    environment:
      APP_DATA_DIR: /var/lib/my-files
    volumes:
      - file-data:/var/lib/my-files
    expose:
      - "8000"
    restart: unless-stopped

  setup-auth:
    build:
      context: ./server
    command: ["./file-uploader", "-setup-auth"]
    environment:
      APP_DATA_DIR: /var/lib/my-files
    volumes:
      - file-data:/var/lib/my-files
    stdin_open: true
    tty: true
    profiles:
      - setup

  client:
    build:
      context: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  file-data:
